/** Helm's global Amp plugin. */

import * as os from "node:os";
import * as path from "node:path";
import {
  assertManagedAgentFileWritable,
  managedAgentFileInstalled,
  removeManagedAgentFile,
  writeManagedAgentFile,
} from "./managed-agent-file.js";

export const HELM_AMP_MARKER = "Generated by Helm CLI — managed by `helm hooks`.";

export const HELM_AMP_PLUGIN = `/**
 * ${HELM_AMP_MARKER}
 * Adds shared Helm context before each Amp turn. All Helm calls fail open.
 */
import type { PluginAPI } from "@ampcode/plugin"
import { spawn, spawnSync } from "node:child_process"

export const description = "Inject shared Helm team context into Amp turns."

export default function (amp: PluginAPI) {
  const workspace = amp.system.workspaceRoot
    ? amp.helpers.filePathFromURI(amp.system.workspaceRoot)
    : process.cwd()
  const started = new Set()

  amp.on("agent.start", async (event) => {
    try {
      const sessionId = event.thread.id
      const first = !started.has(sessionId)
      if (first) started.add(sessionId)
      const result = spawnSync("helm", ["inject", "--format", "plugin"], {
        cwd: workspace,
        encoding: "utf-8",
        input: JSON.stringify({
          session_id: sessionId,
          cwd: workspace,
          hook_event_name: first ? "SessionStart" : "UserPromptSubmit",
        }),
        timeout: 2_500,
      })
      const stdout = result.status === 0 ? result.stdout?.trim() ?? "" : ""
      let additionalContext = ""
      let systemMessage = ""
      if (stdout) {
        try {
          const parsed = JSON.parse(stdout)
          additionalContext = typeof parsed?.additionalContext === "string" ? parsed.additionalContext : ""
          systemMessage = typeof parsed?.systemMessage === "string" ? parsed.systemMessage : ""
        } catch {
          additionalContext = stdout
        }
      }
      if (additionalContext) {
        return { message: { content: additionalContext, display: false } }
      }
      if (systemMessage) {
        return { message: { content: systemMessage, display: true } }
      }
    } catch {
      // Helm must never interrupt Amp.
    }
  })

  amp.onDispose(() => {
    try {
      const child = spawn("helm", ["scan", "--days", "2", "--quiet"], {
        detached: true,
        stdio: "ignore",
      })
      child.unref()
    } catch {
      // Best-effort background sync.
    }
  })
}
`;

export function getAmpPluginPath(): string {
  return path.join(os.homedir(), ".config", "amp", "plugins", "helm.ts");
}

export function ampHooksInstalled(filePath = getAmpPluginPath()): boolean {
  return managedAgentFileInstalled(filePath, HELM_AMP_MARKER);
}

export function assertAmpPluginWritable(filePath = getAmpPluginPath()): void {
  assertManagedAgentFileWritable(filePath, HELM_AMP_MARKER);
}

export function writeAmpPlugin(filePath = getAmpPluginPath()): void {
  writeManagedAgentFile(filePath, HELM_AMP_MARKER, HELM_AMP_PLUGIN);
}

export function removeAmpPlugin(filePath = getAmpPluginPath()): boolean {
  return removeManagedAgentFile(filePath, HELM_AMP_MARKER);
}
