/** Helm's standalone user-level GitHub Copilot CLI hook file. */

import * as os from "node:os";
import * as path from "node:path";
import {
  assertManagedAgentFileWritable,
  managedAgentFileInstalled,
  removeManagedAgentFile,
  writeManagedAgentFile,
} from "./managed-agent-file.js";

export const HELM_COPILOT_MARKER = "Generated by Helm CLI — managed by `helm hooks`.";

export const HELM_COPILOT_HOOKS = `${JSON.stringify({
  version: 1,
  description: HELM_COPILOT_MARKER,
  hooks: {
    SessionStart: [
      { type: "command", command: "helm inject --format copilot", timeoutSec: 3 },
    ],
    SessionEnd: [
      { type: "command", command: "helm scan --days 2 --quiet", timeoutSec: 3 },
    ],
  },
}, null, 2)}\n`;

export function getCopilotHooksPath(): string {
  const home = process.env.COPILOT_HOME || path.join(os.homedir(), ".copilot");
  return path.join(home, "hooks", "helm.json");
}

export function copilotHooksInstalled(filePath = getCopilotHooksPath()): boolean {
  return managedAgentFileInstalled(filePath, HELM_COPILOT_MARKER);
}

export function assertCopilotHooksWritable(filePath = getCopilotHooksPath()): void {
  assertManagedAgentFileWritable(filePath, HELM_COPILOT_MARKER);
}

export function writeCopilotHooks(filePath = getCopilotHooksPath()): void {
  writeManagedAgentFile(filePath, HELM_COPILOT_MARKER, HELM_COPILOT_HOOKS);
}

export function removeCopilotHooks(filePath = getCopilotHooksPath()): boolean {
  return removeManagedAgentFile(filePath, HELM_COPILOT_MARKER);
}
