/** Helm's global Kilo plugin (Kilo is OpenCode-compatible, with its own config root). */

import * as os from "node:os";
import * as path from "node:path";
import {
  assertManagedAgentFileWritable,
  managedAgentFileInstalled,
  removeManagedAgentFile,
  writeManagedAgentFile,
} from "./managed-agent-file.js";

export const HELM_KILO_MARKER = "Generated by Helm CLI — managed by `helm hooks`.";

export const HELM_KILO_PLUGIN = `/**
 * ${HELM_KILO_MARKER}
 * Adds shared Helm context to Kilo, retains tool evidence, and learns when idle.
 */
import type { Plugin } from "@kilocode/plugin"
import { spawn, spawnSync } from "node:child_process"

export const HelmPlugin: Plugin = async ({ directory, client }) => {
  let syncStarted = false
  const prompts = new Map<string, string>()

  const runHelm = (args: string[], payload: unknown, timeout = 2_000) => {
    try {
      return spawnSync("helm", args, {
        cwd: directory,
        encoding: "utf-8",
        input: JSON.stringify(payload),
        timeout,
      })
    } catch {
      return null
    }
  }

  return {
    "chat.message": async (
      input: { sessionID: string },
      output: { parts?: Array<{ type?: string; text?: string }> },
    ) => {
      const prompt = output.parts
        ?.filter((part) => part.type === "text" && typeof part.text === "string")
        .map((part) => part.text)
        .join("\n")
        .trim()
      if (prompt) prompts.set(input.sessionID, prompt)
    },

    "experimental.chat.system.transform": async (
      input: { sessionID?: string },
      output: { system: string[] },
    ) => {
      try {
        const sessionID = input.sessionID ?? "kilo-session"
        const result = runHelm(["inject"], {
          session_id: sessionID,
          cwd: directory,
          hook_event_name: "UserPromptSubmit",
          provider: "kilo",
          prompt: prompts.get(sessionID),
        })
        const context = result?.status === 0 ? result.stdout?.trim() : ""
        if (!context) return
        if (output.system.length === 0) output.system.push(context)
        else output.system[0] = output.system[0] + "\\n\\n" + context
      } catch {
        // Helm must never interrupt Kilo.
      }
    },

    "tool.execute.after": async (
      input: { sessionID: string; tool: string; args?: unknown },
      output: unknown,
    ) => {
      runHelm(["observe"], {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: input.tool,
        tool_input: input.args,
        tool_response: output,
      }, 1_000)
    },

    event: async ({ event }: { event: { type: string; properties?: { sessionID?: string } } }) => {
      if (event.type !== "session.idle") return
      const sessionID = event.properties?.sessionID
      if (sessionID) {
        try {
          const response = await client.session.messages({
            path: { id: sessionID },
            query: { limit: 20 },
          })
          const messages = Array.isArray(response) ? response : response.data
          const assistant = [...(messages ?? [])].reverse().find(
            (message: { info?: { role?: string } }) => message.info?.role === "assistant",
          )
          const text = assistant?.parts
            ?.filter((part: { type?: string; text?: string }) =>
              part.type === "text" && typeof part.text === "string"
            )
            .map((part: { text: string }) => part.text)
            .join("\n")
            .trim()
          if (text) runHelm(["learn"], {
            session_id: sessionID,
            cwd: directory,
            provider: "kilo",
            prompt_response: text,
          }, 2_000)
        } catch {
          // Learning remains best-effort.
        }
      }
      if (syncStarted) return
      syncStarted = true
      try {
        const child = spawn("helm", ["scan", "--days", "2", "--quiet"], {
          cwd: directory,
          detached: true,
          stdio: "ignore",
        })
        child.unref()
      } catch {
        // Best-effort background sync.
      }
    },
  }
}
`;

export function getKiloPluginPath(): string {
  return path.join(os.homedir(), ".config", "kilo", "plugin", "helm.ts");
}

export function kiloHooksInstalled(filePath = getKiloPluginPath()): boolean {
  return managedAgentFileInstalled(filePath, HELM_KILO_MARKER);
}

export function assertKiloPluginWritable(filePath = getKiloPluginPath()): void {
  assertManagedAgentFileWritable(filePath, HELM_KILO_MARKER);
}

export function writeKiloPlugin(filePath = getKiloPluginPath()): void {
  writeManagedAgentFile(filePath, HELM_KILO_MARKER, HELM_KILO_PLUGIN);
}

export function removeKiloPlugin(filePath = getKiloPluginPath()): boolean {
  return removeManagedAgentFile(filePath, HELM_KILO_MARKER);
}
