/** Helm's global OpenCode plugin. OpenCode auto-loads files in this folder. */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

export const HELM_OPENCODE_MARKER = "Generated by Helm CLI — managed by `helm hooks`.";

export const HELM_OPENCODE_PLUGIN = `/**
 * ${HELM_OPENCODE_MARKER}
 * Injects shared context into every OpenCode model request, retains bounded
 * tool evidence, and learns from completed turns. All Helm calls fail open.
 */
import type { Plugin } from "@opencode-ai/plugin"
import { spawn, spawnSync } from "node:child_process"

export const HelmPlugin: Plugin = async ({ directory, client }) => {
  let syncStarted = false
  const prompts = new Map<string, string>()

  const runHelm = (args: string[], payload: unknown, timeout = 2_000) => {
    try {
      return spawnSync("helm", args, {
        cwd: directory,
        encoding: "utf-8",
        input: JSON.stringify(payload),
        timeout,
      })
    } catch {
      return null
    }
  }

  return {
    "chat.message": async (
      input: { sessionID: string },
      output: { parts?: Array<{ type?: string; text?: string }> },
    ) => {
      const prompt = output.parts
        ?.filter((part) => part.type === "text" && typeof part.text === "string")
        .map((part) => part.text)
        .join("\n")
        .trim()
      if (prompt) prompts.set(input.sessionID, prompt)
    },

    "experimental.chat.system.transform": async (
      input: { sessionID?: string },
      output: { system: string[] },
    ) => {
      try {
        const sessionID = input.sessionID ?? "opencode-session"
        const result = runHelm(["inject", "--format", "plugin"], {
          session_id: sessionID,
          cwd: directory,
          hook_event_name: "UserPromptSubmit",
          provider: "opencode",
          prompt: prompts.get(sessionID),
        })
        const stdout = result?.status === 0 ? result.stdout?.trim() ?? "" : ""
        let additionalContext = ""
        let systemMessage = ""
        if (stdout) {
          try {
            const parsed = JSON.parse(stdout)
            additionalContext = typeof parsed?.additionalContext === "string" ? parsed.additionalContext : ""
            systemMessage = typeof parsed?.systemMessage === "string" ? parsed.systemMessage : ""
          } catch {
            additionalContext = stdout
          }
        }
        if (!additionalContext && !systemMessage) return
        if (additionalContext) {
          if (output.system.length === 0) output.system.push(additionalContext)
          else output.system[0] = output.system[0] + "\\n\\n" + additionalContext
        }
        if (systemMessage) output.system.unshift(systemMessage)
      } catch {
        // Helm must never interrupt OpenCode.
      }
    },

    "tool.execute.after": async (
      input: { sessionID: string; tool: string; args?: unknown },
      output: unknown,
    ) => {
      runHelm(["observe"], {
        session_id: input.sessionID,
        cwd: directory,
        tool_name: input.tool,
        tool_input: input.args,
        tool_response: output,
      }, 1_000)
    },

    event: async ({ event }: { event: { type: string; properties?: { sessionID?: string } } }) => {
      if (event.type !== "session.idle") return
      const sessionID = event.properties?.sessionID
      if (sessionID) {
        try {
          const response = await client.session.messages({
            path: { id: sessionID },
            query: { limit: 20 },
          })
          const messages = Array.isArray(response) ? response : response.data
          const assistant = [...(messages ?? [])].reverse().find(
            (message: { info?: { role?: string } }) => message.info?.role === "assistant",
          )
          const text = assistant?.parts
            ?.filter((part: { type?: string; text?: string }) =>
              part.type === "text" && typeof part.text === "string"
            )
            .map((part: { text: string }) => part.text)
            .join("\n")
            .trim()
          if (text) runHelm(["learn"], {
            session_id: sessionID,
            cwd: directory,
            provider: "opencode",
            prompt_response: text,
          }, 2_000)
        } catch {
          // Learning remains best-effort.
        }
      }
      if (syncStarted) return
      syncStarted = true
      try {
        const child = spawn("helm", ["scan", "--days", "2", "--quiet"], {
          cwd: directory,
          detached: true,
          stdio: "ignore",
        })
        child.unref()
      } catch {
        // Best-effort background sync.
      }
    },
  }
}
`;

export function getOpenCodePluginPath(): string {
  return path.join(os.homedir(), ".config", "opencode", "plugins", "helm.ts");
}

export function openCodeHooksInstalled(pluginPath = getOpenCodePluginPath()): boolean {
  try {
    return fs.readFileSync(pluginPath, "utf-8").includes(HELM_OPENCODE_MARKER);
  } catch {
    return false;
  }
}

function isLegacyHelmPlugin(source: string): boolean {
  return source.includes("Helm plugin for OpenCode") && source.includes("export const HelmPlugin");
}

export function assertOpenCodePluginWritable(pluginPath = getOpenCodePluginPath()): void {
  if (!fs.existsSync(pluginPath)) {
    return;
  }
  const source = fs.readFileSync(pluginPath, "utf-8");
  if (!source.includes(HELM_OPENCODE_MARKER) && !isLegacyHelmPlugin(source)) {
    throw new Error(
      `${pluginPath} already exists and is not managed by Helm — refusing to overwrite it.`,
    );
  }
}

export function writeOpenCodePlugin(pluginPath = getOpenCodePluginPath()): void {
  assertOpenCodePluginWritable(pluginPath);
  fs.mkdirSync(path.dirname(pluginPath), { recursive: true });
  fs.writeFileSync(pluginPath, HELM_OPENCODE_PLUGIN);
}

export function removeOpenCodePlugin(pluginPath = getOpenCodePluginPath()): boolean {
  if (!fs.existsSync(pluginPath)) {
    return false;
  }
  const source = fs.readFileSync(pluginPath, "utf-8");
  if (!source.includes(HELM_OPENCODE_MARKER) && !isLegacyHelmPlugin(source)) {
    return false;
  }
  fs.unlinkSync(pluginPath);
  return true;
}
