/** Helm's global OpenCode plugin. OpenCode auto-loads files in this folder. */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

export const HELM_OPENCODE_MARKER = "Generated by Helm CLI — managed by `helm hooks`.";

export const HELM_OPENCODE_PLUGIN = `/**
 * ${HELM_OPENCODE_MARKER}
 * Injects shared context into every OpenCode model request and starts a quiet
 * usage sync when a session becomes idle. All Helm calls fail open.
 */
import type { Plugin } from "@opencode-ai/plugin"
import { spawn, spawnSync } from "node:child_process"

export const HelmPlugin: Plugin = async ({ directory }) => {
  let syncStarted = false

  return {
    "experimental.chat.system.transform": async (
      input: { sessionID?: string },
      output: { system: string[] },
    ) => {
      try {
        const result = spawnSync("helm", ["inject"], {
          cwd: directory,
          encoding: "utf-8",
          input: JSON.stringify({
            session_id: input.sessionID ?? "opencode-session",
            cwd: directory,
            hook_event_name: "UserPromptSubmit",
          }),
          timeout: 2_000,
        })
        const context = result.status === 0 ? result.stdout?.trim() : ""
        if (!context) return

        // Keep one system block for providers that require a single system message.
        if (output.system.length === 0) output.system.push(context)
        else output.system[0] = output.system[0] + "\\n\\n" + context
      } catch {
        // Helm must never interrupt OpenCode.
      }
    },

    event: async ({ event }: { event: { type: string } }) => {
      if (event.type !== "session.idle" || syncStarted) return
      syncStarted = true
      try {
        const child = spawn("helm", ["scan", "--days", "2", "--quiet"], {
          cwd: directory,
          detached: true,
          stdio: "ignore",
        })
        child.unref()
      } catch {
        // Best-effort background sync.
      }
    },
  }
}
`;

export function getOpenCodePluginPath(): string {
  return path.join(os.homedir(), ".config", "opencode", "plugins", "helm.ts");
}

export function openCodeHooksInstalled(pluginPath = getOpenCodePluginPath()): boolean {
  try {
    return fs.readFileSync(pluginPath, "utf-8").includes(HELM_OPENCODE_MARKER);
  } catch {
    return false;
  }
}

function isLegacyHelmPlugin(source: string): boolean {
  return source.includes("Helm plugin for OpenCode") && source.includes("export const HelmPlugin");
}

export function assertOpenCodePluginWritable(pluginPath = getOpenCodePluginPath()): void {
  if (!fs.existsSync(pluginPath)) {
    return;
  }
  const source = fs.readFileSync(pluginPath, "utf-8");
  if (!source.includes(HELM_OPENCODE_MARKER) && !isLegacyHelmPlugin(source)) {
    throw new Error(
      `${pluginPath} already exists and is not managed by Helm — refusing to overwrite it.`,
    );
  }
}

export function writeOpenCodePlugin(pluginPath = getOpenCodePluginPath()): void {
  assertOpenCodePluginWritable(pluginPath);
  fs.mkdirSync(path.dirname(pluginPath), { recursive: true });
  fs.writeFileSync(pluginPath, HELM_OPENCODE_PLUGIN);
}

export function removeOpenCodePlugin(pluginPath = getOpenCodePluginPath()): boolean {
  if (!fs.existsSync(pluginPath)) {
    return false;
  }
  const source = fs.readFileSync(pluginPath, "utf-8");
  if (!source.includes(HELM_OPENCODE_MARKER) && !isLegacyHelmPlugin(source)) {
    return false;
  }
  fs.unlinkSync(pluginPath);
  return true;
}
