/** Helm's global Pi extension. */

import * as os from "node:os";
import * as path from "node:path";
import {
  assertManagedAgentFileWritable,
  managedAgentFileInstalled,
  removeManagedAgentFile,
  writeManagedAgentFile,
} from "./managed-agent-file.js";

export const HELM_PI_MARKER = "Generated by Helm CLI — managed by `helm hooks`.";

export const HELM_PI_EXTENSION = `/**
 * ${HELM_PI_MARKER}
 * Adds shared Helm context before each Pi turn. All Helm calls fail open.
 */
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent"
import { spawn, spawnSync } from "node:child_process"
import { randomUUID } from "node:crypto"

export default function (pi: ExtensionAPI) {
  const sessionId = randomUUID()

  pi.on("before_agent_start", async (event, ctx) => {
    try {
      const cwd = event.systemPromptOptions.cwd ?? ctx.cwd
      const result = spawnSync("helm", ["inject", "--format", "plugin"], {
        cwd,
        encoding: "utf-8",
        input: JSON.stringify({
          session_id: sessionId,
          cwd,
          hook_event_name: "UserPromptSubmit",
        }),
        timeout: 2_500,
      })
      const stdout = result.status === 0 ? result.stdout?.trim() ?? "" : ""
      let additionalContext = ""
      let systemMessage = ""
      if (stdout) {
        try {
          const parsed = JSON.parse(stdout)
          additionalContext = typeof parsed?.additionalContext === "string" ? parsed.additionalContext : ""
          systemMessage = typeof parsed?.systemMessage === "string" ? parsed.systemMessage : ""
        } catch {
          additionalContext = stdout
        }
      }
      if (additionalContext) {
        return { message: { customType: "helm-team-context", content: additionalContext, display: false } }
      }
      if (systemMessage) {
        return { message: { customType: "helm-visible", content: systemMessage, display: true } }
      }
    } catch {
      // Helm must never interrupt Pi.
    }
  })

  pi.on("session_shutdown", () => {
    try {
      const child = spawn("helm", ["scan", "--days", "2", "--quiet"], {
        detached: true,
        stdio: "ignore",
      })
      child.unref()
    } catch {
      // Best-effort background sync.
    }
  })
}
`;

export function getPiExtensionPath(): string {
  return path.join(os.homedir(), ".pi", "agent", "extensions", "helm.ts");
}

export function piHooksInstalled(filePath = getPiExtensionPath()): boolean {
  return managedAgentFileInstalled(filePath, HELM_PI_MARKER);
}

export function assertPiExtensionWritable(filePath = getPiExtensionPath()): void {
  assertManagedAgentFileWritable(filePath, HELM_PI_MARKER);
}

export function writePiExtension(filePath = getPiExtensionPath()): void {
  writeManagedAgentFile(filePath, HELM_PI_MARKER, HELM_PI_EXTENSION);
}

export function removePiExtension(filePath = getPiExtensionPath()): boolean {
  return removeManagedAgentFile(filePath, HELM_PI_MARKER);
}
